name: Run Rust Status Checker

on:
  workflow_dispatch: # यह आपको GitHub पर 'Run workflow' का बटन देगा

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and Run
        run: cargo run --release